plugins {
    id 'java'
}

group = 'com.example'
version = '1.0.0'

repositories {
    mavenCentral()
}

ext {
    elasticVersion = '9.4.1'
}

dependencies {
    compileOnly "org.elasticsearch:elasticsearch:${elasticVersion}"
    implementation 'com.ip2location:ip2location-java:8.13.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}